# Generated by Django 5.1.5 on 2025-01-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='content',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='tags',
            field=models.ManyToManyField(related_name='tasks', to='todo_app.tagmodel'),
        ),
    ]
