# Generated by Django 5.1.5 on 2025-01-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_taskmodel_content_alter_taskmodel_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='content',
            field=models.CharField(max_length=80),
        ),
    ]
